---
title: Todd Stoffer
timezone: UTC
collections:
  posts:
    title: Posts
    output: true
  uploads:
    title: Uploads
    output: true
locale: en_US
logo: 
url: https://toddstoffer.github.io
owner:
  name: Todd Stoffer
  avatar: bio-photo.jpg
  bio: Hi I'm Todd, I'm a Librarian
  email: tdstoffe@ncsu.edu
  disqus-shortname: 
  twitter: toddstoffer
  facebook: 
  google:
    plus: 
    analytics: 
    verify: 
    ad-client: 
    ad-slot: 
  bing-verify: 
  github: toddstoffer
  stackoverflow: 
  linkedin: toddstoffer
  xing: 
  instagram: toddstoffer
  lastfm: 
  tumblr: 
  pinterest: 
  foursquare: 
  steam: 
  dribbble: 
  youtube: 
  soundcloud: 
  weibo: 
  flickr: 
  codepen: 
permalink: "/:categories/:title/"
markdown: kramdown
highlighter: rouge
sass:
  sass_dir: _sass
  style: compressed
kramdown:
  auto_ids: true
  footnote_nr: 1
  entity_output: as_char
  toc_levels: 1..6
  enable_coderay: false
include:
- ".htaccess"
exclude:
- lib
- config.rb
- Capfile
- config
- log
- Rakefile
- Rakefile.rb
- tmp
- less
- "*.sublime-project"
- "*.sublime-workspace"
- test
- spec
- Gruntfile.js
- package.json
- node_modules
- Gemfile
- Gemfile.lock
- LICENSE
- README.md
